on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm run build
    - uses: oneyedev/deploy-s3@v1
      with:
        public-root: "./dist"
        region: "ap-northeast-2"
        bucket: "s3-deploy-test.oneyedev.com"